### ISSUE TITLE
Latest docker image: error while loading shared libraries

### ISSUE THREAD

**Issue by AtomicMaya** [WtfJoke/tectonic-docker#4]
Hi!

Whilst following your documentation on running the image (`dxjoke/tectonic-docker:latest`) locally, when  running `tectonic --keep-intermediates --reruns 0 main.tex`, I get the following error:
`tectonic: error while loading shared libraries: libicuuc.so.67: cannot open shared object file: No such file or directory`

I have confirmed this happens with the last 3 images of `tectonic-docker`:
- 0.8.0-buster-biber
- 0.7.1-buster-biber
- 0.6.4-buster-biber

Assuming this isn't a client-side issue due to the nature of Docker, I wanted to inform you of this development.

**Comment by PHPirates** [comment]
I created a PR that should fix it. You can use `phpirates/tectonic-docker:0.8.0` until @WtfJoke published a fixed version.
Thanks for reporting!

**Comment by AtomicMaya** [comment]
Hiya @PHPirates thanks for the PR.

Quick question though: I'm assuming `tectonic: command not found` should not be expected behavior?

**Comment by PHPirates** [comment]
Where do you get that? I just pulled my image again to double check and it really works for me.

```
docker run -it phpirates/tectonic-docker:0.8.0
tectonic --version
printf '\\documentclass{article} \\begin{document} hi \\end{document}' > main.tex
tectonic main.tex
```

**Comment by AtomicMaya** [comment]
Sorry for the misunderstanding, it does work within Docker itself, but somehow not in gitlab CI... 

Update: I'm an idiot. I forgot I'd set up my runner to be in a `shell` environment and not `docker`.
It works as expected, thanks.

I'll let @WtfJoke close the issue when the PR passes.

**Comment by WtfJoke** [comment]
Thank you both for reporting and creating a PR :)

Do you experience this issue with any latex document? Because during the build of the docker image tectonic is executed on the .tex files of this repo. 

If not, could you provide a minimal reproducable example (so I might can extend the .tex files) in order to prevent similar issues in future.

**Comment by PHPirates** [comment]
@WtfJoke The tectonic in the latest image doesn't work at all, please check yourself:

```
docker run -it dxjoke/tectonic-docker
tectonic --version
```

I don't understand how an image that worked when uploaded to docker hub breaks though, I thought a Docker image is like the same every time you pull it. If you find out, please enlighten me.

**Comment by WtfJoke** [comment]
Strange 🤔 I'll take a look at your PR tomorrow.

**Comment by WtfJoke** [comment]
>docker run -it dxjoke/tectonic-docker
root@2cd0afee0e11:/usr/src/tex# tectonic --version
Tectonic 0.1.11
root@2cd0afee0e11:/usr/src/tex# exit
exit

hmm...

**Comment by WtfJoke** [comment]
I guess it has to do with the environment where the docker image is built. A locally built one works.

I guess the sheduled job has destroyed the existing images.

**Comment by WtfJoke** [comment]
I've merged #5 and verified it works. 

I'll try to build:
    0.8.0-buster-biber
    0.7.1-buster-biber
    0.6.4-buster-biber
locally and update docker hub so that they still works if somebody uses them.

Keep you posted, thanks for opening the issue :)

EDIT: I think it might have to do with the used rust version where the image is built... My rust image is 1 year old

**Comment by WtfJoke** [comment]
> * 0.8.0-buster-biber
> 
> * 0.7.1-buster-biber
> 
> * 0.6.4-buster-biber

I reuploaded them and they should work now again.



> I think it might have to do with the used rust version where the image is built... My rust image is 1 year old

I just confirmed this as the issue. I've deleted my local rust image and used the newest latest image and were able to build a corrupt image:
```
docker run e23705bddd0c0f60a432c2bcfa1b027a11d4f3c3ed92db722060dd58701e9f00 tectonic --version
tectonic: error while loading shared libraries: libicuuc.so.67: cannot open shared object file: No such file or directory
```

When changing it to `rust:buster` the image worked flawlessly however. So that was the issue  🕵️ 🐛 

I've also changed `rust:latest` to `rust:bullseye` now (https://github.com/WtfJoke/tectonic-docker/commit/fbd739baa6f8048993c2109110b4703165fb902f) so we dont have this issue in future again :)

**Comment by PHPirates** [comment]
Aha, clear, thanks a lot for the research and fix!

**Comment by WtfJoke** [comment]
Thanks a lot for your PR and the issue report  @AtomicNicos of course :) thats how I like open source :)

**Comment by AtomicMaya** [comment]
Pleasure "helping out" 😅
